<a href="https://colab.research.google.com/github/PedroAlmeida18/CalculoNumerico/blob/main/Elimina%C3%A7%C3%A3oGausseana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
from binascii import b2a_base64
import numpy as np
def gauss(A,b):
  # A é a matriz dos coeficientes
  # b é o vetor de termos independentes

  n = len(b)

  for k in range(0, n-1): #Percorre a diagonal
     for i in range(k+1, n): #Percorre as linhas
        m = A[i][k] / A[k][k]

        for j in range(k,n): # Percorre as colunas
          A[i][j] = A[i][j] - m * A[k][j]

        b[i] = b[i] - m*b[k]

  return A,b # depois de ter feito o escalonamento

def subs_reversa(A_t,b_t):

    n = len(b)

    x = n*[0] #Vetor Solution

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b
def Hilbert(n):
  A = np.zeros((n,n))

  b = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    b[i] = s

  return A, b





#Teste
n = int (input("DIGITE O VALOR DE N QUE DESEJA PARA FAZER A ELIMINAÇÃO GAUSSEANA COM MATRIZ DE HILBERT :" ))
A, b = Hilbert(n)
A_t,b_t= gauss(A,b);
print(A_t)
print(20*'__')
print(b_t)
print(20*'__')

x = subs_reversa(A_t, b_t)
print(x)


DIGITE O VALOR DE N QUE DESEJA PARA FAZER A ELIMINAÇÃO GAUSSEANA COM MATRIZ DE HILBERT :3
[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03]]
________________________________________
[1.8333333333333333, 0.16666666666666663, 0.0055555555555554526]
________________________________________
[0.999999999999998, 1.0000000000000122, 0.9999999999999875]


In [31]:
def Hilbert(n):
  A = np.zeros((n,n))

  b = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    b[i] = s

  return A, b