<a href="https://colab.research.google.com/github/PedroAlmeida18/CalculoNumerico/blob/main/Elimina%C3%A7%C3%A3oGausseana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
def gauss(A,b):
  # A é a matriz dos coeficientes
  # b é o vetor de termos independentes

  n = len(b)

  for k in range(0, n-1): #Percorre a diagonal
     pivo = A[k][k]

     for i in range(k+1, n): #Percorre as linhas
        m = A[i][k] / pivo

        for j in range(k,n): # Percorre as colunas
          A[i][j] = A[i][j] - m * A[k][j]

        b[i] = b[i] - m*b[k]

  return A,b # depois de ter feito o escalonamento

#Teste
A = [[3,2,4], [1,1,2], [4,3,-2]]
b = [1,2,3]

A_t,b_t = gauss(A,b)

print(np.array(A_t))

print("-----------------------")

print(b_t)

[[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]
-----------------------
[1, 1.6666666666666667, -4.440892098500626e-16]


In [30]:
def subs_reversa(A_t,b_t):

    n = len(b)

    x = n*[0] #Vetor Solution

    x[n-1] = b[n-1] / A[n-1][n-1]

    for k in range(n-2,-1,-1):
      s = 0
      for j in range(k+1,n):
        s = s +A[k][j]*x[j]


      x[k] = (b[k] - s) / A[k][k]

    return x # retorna a solução do SL A*x = b

    #teste

x = subs_reversa(A_t,b_t)
print(x)


[-3.0, 5.0, 5.551115123125783e-17]


In [33]:
def Hilbert(n):
    b = n*[0]

    A = n*[n*[0]]

    return A,b